version: '3'
services:
    web:
        build: .
        volumes: 
            - "./app:/src/app"
        image: node:alpine
        ports:
            - "1111:1111"
        environment: 
            - NJSPORT=1111